#!/usr/bin/env node
// Builds the browser app into docs/, which is what GitHub Pages serves.
//
// The point of this build is that it is the SAME engine: the browser bundle
// imports the identical redaction, parser, consolidation, PFIC cascade and
// report renderer the CLI uses. Nothing is reimplemented for the web, so the
// two cannot drift and produce different numbers.
//
// Node built-ins are stubbed rather than polyfilled. The browser path never
// touches the filesystem — the vault lives in memory, params arrive as bundled
// JSON, and hashing uses SubtleCrypto — so a stub that throws is the honest
// shape: if a browser code path ever reaches for the disk, it fails loudly
// instead of silently doing something else.
import { build } from "esbuild";
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs");

// Regenerate the inlined worked example so it cannot drift from the fixtures.
const statements = {};
for (const dir of readdirSync(join(ROOT, "test/fixtures/statements"))) {
  for (const file of readdirSync(join(ROOT, "test/fixtures/statements", dir))) {
    statements[`${dir}/${file}`] = readFileSync(join(ROOT, "test/fixtures/statements", dir, file), "utf8");
  }
}
writeFileSync(
  join(ROOT, "src/web/demo-statements.ts"),
  "// Generated by scripts/build-web.mjs — the synthetic fixtures, inlined so the\n" +
    "// worked example runs with no network at all. All fictional (see NOTICE).\n" +
    `export const DEMO_STATEMENTS: Record<string, string> = ${JSON.stringify(statements, null, 2)};\n`
);

const stubNodeBuiltins = {
  name: "stub-node-builtins",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^node:(fs|path|url|crypto|os|child_process)$/ }, (args) => ({
      path: args.path,
      namespace: "node-stub",
    }));
    pluginBuild.onLoad({ filter: /.*/, namespace: "node-stub" }, (args) => {
      const module = args.path.replace("node:", "");
      const unavailable = (name) =>
        `export function ${name}() { throw new Error("${module}.${name} is not available in the browser build — ` +
        `this path should never run client-side"); }`;
      const shims = {
        // join/dirname/fileURLToPath run at module load for path constants that
        // the browser never dereferences, so they return harmless values.
        path: `export const join = (...p) => p.join("/");
export const dirname = (p) => String(p).replace(/\\/[^/]*$/, "");
export const basename = (p) => String(p).split("/").pop();
export const resolve = (...p) => p.join("/");
export default { join, dirname, basename, resolve };`,
        url: `export const fileURLToPath = (u) => String(u);
export default { fileURLToPath };`,
        fs: [
          "readFileSync",
          "writeFileSync",
          "existsSync",
          "chmodSync",
          "mkdirSync",
          "readdirSync",
          "statSync",
          "appendFileSync",
          "rmSync",
        ]
          .map(unavailable)
          .join("\n"),
        crypto: unavailable("createHash"),
        os: unavailable("tmpdir"),
        child_process: unavailable("execFileSync"),
      };
      return { contents: shims[module] ?? unavailable("unsupported"), loader: "js" };
    });
  },
};

mkdirSync(OUT, { recursive: true });

const result = await build({
  entryPoints: [join(ROOT, "src/web/app.ts")],
  bundle: true,
  format: "esm",
  target: ["es2022"],
  outfile: join(OUT, "app.js"),
  minify: true,
  sourcemap: false,
  loader: { ".json": "json" },
  plugins: [stubNodeBuiltins],
  logLevel: "warning",
  define: { "process.env.NODE_ENV": '"production"' },
  metafile: true,
});

copyFileSync(join(ROOT, "src/web/index.html"), join(OUT, "index.html"));
// Tell GitHub Pages not to run the output through Jekyll.
writeFileSync(join(OUT, ".nojekyll"), "");

const bytes = Object.values(result.metafile.outputs).reduce((total, output) => total + output.bytes, 0);
console.log(`Built docs/ — ${(bytes / 1024).toFixed(0)}KB of JavaScript, plus index.html`);
